sudo: required

dist: xenial

language:
  - c++

jdk:
  - oraclejdk8  # Building Bazel requires JDK8.

addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg'
      - llvm-toolchain-xenial-7
    packages:
      - bazel
      - clang-format-7
      - clang-7

script: 
  - bash format.sh
  - bazel clean && bazel build //...
  - bazel clean && bazel test --test_output=errors --strategy=TestRunner=standalone //...
